package io.github.kgma74.relaix.security

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.inject.Inject
import javax.inject.Singleton

/**
 * AES-GCM through the AndroidKeyStore.
 *
 * The key material never leaves the keystore — on a device with a secure
 * element it never enters application memory at all — so a backup, a stolen
 * DataStore file, or a `run-as` on a debuggable build yields ciphertext and
 * nothing else. That is the whole reason the device token is not just written
 * as a string: it is a long-lived credential that lets a phone act as this
 * device against the control plane.
 *
 * GCM is authenticated encryption, so a tampered blob fails to decrypt rather
 * than silently producing garbage that would be sent as a token.
 */
@Singleton
class KeyStoreSecretCipher @Inject constructor() : SecretCipher {

    override fun encrypt(plaintext: String): String {
        val cipher = Cipher.getInstance(TRANSFORMATION).apply {
            init(Cipher.ENCRYPT_MODE, secretKey())
        }
        val ciphertext = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))

        // The IV is generated by the provider and must be kept: prefixing it
        // keeps the stored value a single self-contained string, so callers
        // never have to manage two coupled fields.
        val iv = cipher.iv
        val blob = ByteArray(1 + iv.size + ciphertext.size)
        blob[0] = iv.size.toByte()
        iv.copyInto(blob, destinationOffset = 1)
        ciphertext.copyInto(blob, destinationOffset = 1 + iv.size)

        return Base64.encodeToString(blob, Base64.NO_WRAP)
    }

    override fun decrypt(blob: String): String {
        val bytes = Base64.decode(blob, Base64.NO_WRAP)
        require(bytes.isNotEmpty()) { "encrypted blob is empty" }

        val ivSize = bytes[0].toInt()
        require(ivSize in 1 until bytes.size) { "encrypted blob is malformed" }

        val iv = bytes.copyOfRange(1, 1 + ivSize)
        val ciphertext = bytes.copyOfRange(1 + ivSize, bytes.size)

        val cipher = Cipher.getInstance(TRANSFORMATION).apply {
            init(Cipher.DECRYPT_MODE, secretKey(), GCMParameterSpec(TAG_LENGTH_BITS, iv))
        }
        return String(cipher.doFinal(ciphertext), Charsets.UTF_8)
    }

    /**
     * Fetches the key, creating it on first use. Not cached: the keystore
     * handle is cheap, and holding a stale reference across a key
     * invalidation is a failure that only shows up much later.
     */
    private fun secretKey(): SecretKey {
        val keyStore = KeyStore.getInstance(PROVIDER).apply { load(null) }
        (keyStore.getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER)
        generator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                // Deliberately not setUserAuthenticationRequired: the agent
                // must reconnect and send after a reboot with nobody holding
                // the phone. Requiring a screen unlock would make an unattended
                // node stop working, which is the opposite of the point.
                .build(),
        )
        return generator.generateKey()
    }

    private companion object {
        const val PROVIDER = "AndroidKeyStore"
        const val KEY_ALIAS = "relaix_device_token"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val TAG_LENGTH_BITS = 128
    }
}
